{
    'vi_data_path': 'tts_dict_prepare/',
    'en_data_path': 'tts_dict_prepare/',
    'test_en_data_path': 'tts_dict_prepare/',
    'epochs': 20,
    'batch_size': 100,
    'max_len': 30,  # max length of grapheme/phoneme sequences
    'beam_size': 20,  # size of beam for beam-search
    'd_embed': 550,  # embedding dimension
    'd_hidden': 550,  # hidden dimension
    'attention': True,  # use attention or not
    'log_every': 10,  # number of iterations to log and validate training
    'lr': 0.01,  # initial learning rate
    'lr_decay': 0.5,  # decay lr when not observing improvement in val_loss
    'lr_min': 1.0e-5,  # stop when lr is too low
    'n_bad_loss': 5,  # number of bad val_loss before decaying
    'clip': 2.3,  # clip gradient, to avoid exploding gradient
    'cuda': True,  # using gpu or not
    'seed': 5,  # initial seed
    'intermediate_path': 'intermediate/g2p_vi/v2',  # path to save models
    'best_model':'intermediate/g2p_vi/v2/best_model_adagrad_attn_300.pth',
}